# Generated by Django 3.1.7 on 2021-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Xeberi daxil edin'),
        ),
    ]
