# Generated by Django 3.1.7 on 2021-04-15 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210415_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ('-created',), 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='partners',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
